---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-dc1
  namespace: c7a
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    interface: cassandra-dc1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-dc2
  namespace: c7a
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    interface: cassandra-dc2
